import React from 'react';
import {
  Sparkles,
  RotateCcw,
  Printer,
  CheckCircle2,
  AlertTriangle,
  FileDown,
  Layers,
  Leaf,
  Flame,
  Info
} from 'lucide-react';
import { cropData } from '../data/cropData';
import { translations } from '../data/translations';
import RecommendationCard from './RecommendationCard';
import ImpactCard from './ImpactCard';
import DisclaimerCard from './DisclaimerCard';

export default function ResultsSection({
  language,
  imagePreview,
  analysisResult,
  onReset
}) {
  const t = translations[language];

  const topLabel = analysisResult?.topLabel || "Paddy Straw";
  const confidence = analysisResult?.confidence || 96.4;
  const isDemoMode = analysisResult?.isDemoMode ?? true;
  const predictions = analysisResult?.predictions || [];

  // Match crop data from data dictionary
  const currentCrop = cropData[topLabel] || cropData["Paddy Straw"];

  const handlePrint = () => {
    window.print();
  };

  const handleSaveGuide = () => {
    // Generate text summary report to download
    const title = `${currentCrop.name.en} - Value Addition Guide`;
    const content = `================================================
${title}
Generated by CropWaste Finder AI
================================================

Predicted Residue: ${currentCrop.name[language]} (${topLabel})
AI Confidence Match: ${confidence}%
Mode: ${isDemoMode ? 'Demo Classification' : 'TensorFlow.js Live Inference'}

--- RECOMMENDED VALUE-ADDITION ALTERNATIVES ---
${currentCrop.alternatives.map((alt, idx) => `
${idx + 1}. ${alt.title[language]} (${alt.badge[language]})
   Summary: ${alt.summary[language]}
   Economic Benefit: ${alt.economicBenefit[language]}
   Environmental Benefit: ${alt.environmentalBenefit[language]}
   Implementation Steps:
   ${alt.steps[language].map((s, si) => `  - Step ${si + 1}: ${s}`).join('\n')}
`).join('\n')}

--- ENVIRONMENTAL IMPACT ---
"${t.impactHeadline}"
"${t.impactSubline}"

--- ADVISORY DISCLAIMER ---
"${t.disclaimerText}"
`;

    const blob = new Blob([content], { type: 'text/plain;charset=utf-8' });
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.download = `CropWaste_Guide_${currentCrop.id}.txt`;
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
  };

  return (
    <div className="w-full max-w-5xl mx-auto py-6 sm:py-8 px-4">
      
      {/* Top Banner Card with Predicted Residue & Confidence */}
      <div className="rounded-3xl bg-white border border-agri-cream-400 p-6 sm:p-8 shadow-card-agri mb-8">
        
        <div className="flex flex-col lg:flex-row items-center gap-6 sm:gap-8">
          
          {/* Image Thumbnail */}
          <div className="relative w-44 h-44 sm:w-52 sm:h-52 rounded-2xl overflow-hidden border-2 border-agri-green-500/40 bg-agri-cream-200 shrink-0 shadow-md">
            <img
              src={imagePreview}
              alt={currentCrop.name[language]}
              className="w-full h-full object-cover"
            />
            <span className="absolute bottom-2 left-2 px-2.5 py-1 rounded-lg text-xs font-extrabold bg-agri-green-900/90 text-white backdrop-blur-xs">
              ✓ {t.identifiedLabel}
            </span>
          </div>

          {/* Identification Details */}
          <div className="flex-1 text-center lg:text-left space-y-3">
            
            {/* Top Badges */}
            <div className="flex flex-wrap items-center justify-center lg:justify-start gap-2">
              <span className="inline-flex items-center gap-1.5 px-3 py-1 rounded-full text-xs font-extrabold bg-agri-green-100 text-agri-green-900 border border-agri-green-300">
                <CheckCircle2 className="w-4 h-4 text-agri-green-700" />
                {t.identifiedLabel}
              </span>

              {isDemoMode && (
                <span className="inline-flex items-center gap-1.5 px-3 py-1 rounded-full text-xs font-bold bg-amber-100 text-amber-900 border border-amber-300">
                  <Sparkles className="w-3.5 h-3.5 text-amber-700" />
                  {t.demoModeBadge}
                </span>
              )}
            </div>

            {/* Crop Name */}
            <div>
              <h1 className="text-3xl sm:text-4xl font-black text-agri-green-950 font-sans tracking-tight">
                {currentCrop.name[language]}
              </h1>
              <p className="text-sm font-semibold text-agri-brown-600 italic">
                {currentCrop.scientificName}
              </p>
            </div>

            {/* Description */}
            <p className="text-sm text-agri-brown-800 font-medium max-w-xl">
              {currentCrop.description[language]}
            </p>

            {/* Confidence Score Bar */}
            <div className="pt-2 max-w-md">
              <div className="flex items-center justify-between text-xs font-extrabold text-agri-brown-900 mb-1.5">
                <span>{t.confidenceLabel}:</span>
                <span className="text-agri-green-700 text-sm font-black">{confidence}%</span>
              </div>
              <div className="w-full h-3 rounded-full bg-agri-cream-300 overflow-hidden">
                <div
                  className="h-full bg-gradient-to-r from-agri-green-500 to-agri-green-700 rounded-full transition-all duration-1000 ease-out"
                  style={{ width: `${Math.min(confidence, 100)}%` }}
                />
              </div>
            </div>

            {/* Secondary Predictions Breakdown */}
            {predictions.length > 1 && (
              <div className="flex flex-wrap items-center justify-center lg:justify-start gap-3 pt-2 text-xs text-agri-brown-600 font-medium">
                <span className="text-agri-brown-500 font-bold">{t.alternatePossibilities}:</span>
                {predictions.slice(1).map((p, idx) => (
                  <span key={idx} className="px-2 py-0.5 rounded-md bg-agri-cream-200 border border-agri-cream-300">
                    {p.className}: {(p.probability * 100).toFixed(1)}%
                  </span>
                ))}
              </div>
            )}

          </div>

          {/* Action Buttons Column */}
          <div className="flex flex-row lg:flex-col gap-2.5 w-full lg:w-48 shrink-0 no-print">
            <button
              onClick={onReset}
              className="flex-1 inline-flex items-center justify-center gap-2 px-4 py-3 rounded-2xl bg-agri-green-700 hover:bg-agri-green-800 text-white font-bold text-sm shadow-sm hover:shadow-md transition-all duration-200"
            >
              <RotateCcw className="w-4 h-4" />
              <span>{t.resetButton}</span>
            </button>

            <button
              onClick={handleSaveGuide}
              className="flex-1 inline-flex items-center justify-center gap-2 px-4 py-2.5 rounded-2xl bg-white hover:bg-agri-cream-200 text-agri-brown-900 border border-agri-cream-400 font-bold text-xs shadow-xs transition-colors"
            >
              <FileDown className="w-4 h-4 text-agri-brown-700" />
              <span>{t.downloadAdvice}</span>
            </button>

            <button
              onClick={handlePrint}
              className="flex-1 inline-flex items-center justify-center gap-2 px-4 py-2.5 rounded-2xl bg-white hover:bg-agri-cream-200 text-agri-brown-900 border border-agri-cream-400 font-bold text-xs shadow-xs transition-colors"
            >
              <Printer className="w-4 h-4 text-agri-brown-700" />
              <span>{t.printReport}</span>
            </button>
          </div>

        </div>

      </div>

      {/* Required Impact Card */}
      <ImpactCard language={language} />

      {/* Recommendations Section Header */}
      <div className="text-center sm:text-left mb-6">
        <h2 className="text-2xl sm:text-3xl font-black text-agri-green-950 font-sans tracking-tight">
          {t.resultsTitle}
        </h2>
        <p className="text-sm sm:text-base text-agri-brown-700 font-medium mt-1">
          {t.resultsSubtitle}
        </p>
      </div>

      {/* Recommendations Grid */}
      <div className="grid grid-cols-1 md:grid-cols-3 gap-6 mb-8">
        {currentCrop.alternatives.map((rec, index) => (
          <RecommendationCard
            key={rec.id || index}
            recommendation={rec}
            index={index}
            language={language}
          />
        ))}
      </div>

      {/* Required Disclaimer Card */}
      <DisclaimerCard language={language} />

      {/* Bottom Reset Button */}
      <div className="mt-8 text-center no-print">
        <button
          onClick={onReset}
          className="inline-flex items-center gap-2 px-8 py-3.5 rounded-2xl bg-agri-green-800 hover:bg-agri-green-900 text-white font-bold text-base shadow-md hover:shadow-lg transition-all duration-200"
        >
          <RotateCcw className="w-5 h-5" />
          <span>{t.resetButton}</span>
        </button>
      </div>

    </div>
  );
}
